### ISSUE TITLE
train file

### ISSUE THREAD

**Issue by MohammadHossein-Bahari** [jzhang538/Argoverse-Data-Preprocess#1]
Hello

Thank you for providing the code.
While you modified the other repo, you do not provide the train.py file. Hence, when using your code and their train.py, we get issues in running train.py.  Like, different keys for data in dataset.py.
Can you please help on this?

Thanks

**Comment by jzhang538** [comment]
> Hello
> 
> Thank you for providing the code.
> While you modified the other repo, you do not provide the train.py file. Hence, when using your code and their train.py, we get issues in running train.py. Like, different keys for data in dataset.py.
> Can you please help on this?
> 
> Thanks

The name of our feature attributes are different from theirs in the original repo. You may need to rewrite the data loader to use our data.
