### ISSUE TITLE
Data processing

### ISSUE THREAD

**Issue by SkylerHuang** [jzhang538/Argoverse-Data-Preprocess#2]
I processed the raw data using your code, but the processed data is inconsistent with the description in your readme, e,g. get agent feature shape [20,4] , not same as [20, 5] in readme, as well as nbrs_feature. I want to know which feature is missing.

Can you please help on this?
Thanks

**Comment by jzhang538** [comment]
Sorry, I delete the agent_id in the final version of released code, as the id information is the same as the order of object in the list. (Same for NBRS_FEATURE)

**Comment by jzhang538** [comment]
> I processed the raw data using your code, but the processed data is inconsistent with the description in your readme, e,g. get agent feature shape [20,4] , not same as [20, 5] in readme, as well as nbrs_feature. I want to know which feature is missing.
> 
> Can you please help on this?
> Thanks

Sorry, I delete the agent_id in the final version of released code, as the id information is the same as the order of object in the list. (Same for NBRS_FEATURE)
