### ISSUE TITLE
How to use lanes_nbrs feature?

### ISSUE THREAD

**Issue by SkylerHuang** [jzhang538/Argoverse-Data-Preprocess#3]
I don’t know how this feature is applied in this model design and why the adjacent lanes are used.
Thanks！

**Comment by jzhang538** [comment]
adjacent lanes are not used. We simply extract that information here for your convenience.

**Comment by jzhang538** [comment]
> I don’t know how this feature is applied in this model design and why the adjacent lanes are used.
> Thanks！

adjacent lanes are not used. We simply extract that information here for your convenience.
